### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by grahammkelly** [crot4lus/project-dropdown#10]
[Enter steps to reproduce:]

1. Opened a file in a specific folder
2. Press the 'X' (close) on the 'Directory' tab/window

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [project-dropdown](https://github.com/crot4lus/project-dropdown) package 0.9.0

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.normalize (path.js:1179:5)
    at Project.module.exports.Project.removePath (/app.asar/src/project.js:284:28)
    at HTMLButtonElement.closeActiveProject (/packages/project-dropdown/lib/project-dropdown.js:85:22)
    at HTMLButtonElement.dispatch (/packages/project-dropdown/node_modules/jquery/dist/jquery.js:4737:27)
    at HTMLButtonElement.elemData.handle (/packages/project-dropdown/node_modules/jquery/dist/jquery.js:4549:28)
```

### Commands

```
```

### Non-Core Packages

```
browser-plus 0.0.87 
Ensime 0.40.0 
hyperclick 0.0.40 
ink 0.6.3 
intentions 1.1.2 
Jude 0.2.9 
julia-client 0.5.12 
language-groovy 0.6.0 
language-julia 0.10.0 
language-scala 1.1.8 
latex-completions 0.3.2 
linter 1.11.23 
project-dropdown 0.9.0 
script 3.14.1 
tool-bar 1.0.1 
uber-juno 0.1.1 
```

**Comment by GlennTaylorDigital** [comment]
Interesting one, I can't reproduce it - however I notice you put your Atom version is 1.14.3 - my version of Atom tells me the latest is 1.14.1 although I don't know if that would be anything to do with it.

I'll take a look on my other device later and see if I can reproduce.
