### ISSUE TITLE
Failed to activate the project-dropdown package

### ISSUE THREAD

**Issue by mattmacadams** [crot4lus/project-dropdown#11]
[Enter steps to reproduce:]

1. Install package on Aton 1.18.0

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [project-dropdown](https://github.com/crot4lus/project-dropdown) package 0.9.0

### Stack Trace

Failed to activate the project-dropdown package

```
At Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at Object.setActiveProject (/packages/project-dropdown/lib/project-dropdown.js:74:46)
    at Object.createOptions (/packages/project-dropdown/lib/project-dropdown.js:133:29)
    at Object.createDropdown (/packages/project-dropdown/lib/project-dropdown.js:59:25)
    at /packages/project-dropdown/lib/project-dropdown.js:20:23)
    at fire (/packages/git-time-machine/node_modules/jquery/dist/jquery.js:3099:30)
    at /packages/git-time-machine/node_modules/jquery/dist/jquery.js:3145:7)
    at jQuery.fn.ready (/packages/git-time-machine/node_modules/jquery/dist/jquery.js:3378:25)
    at Object.activate (/packages/project-dropdown/lib/project-dropdown.js:16:19)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -4:03.2.0 command-palette:toggle (atom-pane.pane.active)
     -3:47.4.0 application:add-project-folder (atom-pane.pane.active)
     -3:44.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:32.7.0 project-manager:save-project (atom-pane.pane)
     -3:08.8.0 project-manager:edit-projects (div.tool-panel.tree-view)
     -2:50.1.0 project-sidebar:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:49.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:25.5.0 project-sidebar:toggle (atom-pane.pane)
     -2:01.1.0 core:confirm (div.panels-item)
     -0:02.0 core:select-all (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-material-syntax 1.0.6 
autocomplete-clang 0.11.3 
build 0.68.0 
chmod 0.1.1 
file-icons 2.1.8 
git-control 0.9.0 
git-projects 1.17.0 
git-time-machine 1.5.9 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.2 
minimap 4.28.2 
nord-atom-ui 0.11.0 
platformio-ide 2.0.0-beta.6 
platformio-ide-debugger 1.2.3 
platformio-ide-terminal 2.5.1 
project-dropdown 0.9.0 
project-manager 3.3.5 
project-plus 1.0.0 
tree-view-git-projects 0.5.0 
tree-view-git-status 1.4.0 
```

**Comment by GlennTaylorDigital** [comment]
Hi, apologies for the late delay - stupidly I haven't updated Atom for a while so I've only just come across the issue myself. Currently looking in to a fix!

**Comment by GlennTaylorDigital** [comment]
I've pushed a temporary fix for this issue, awaiting a response from Atom on an issue.
