### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by siteleas** [crot4lus/project-dropdown#3]
[Enter steps to reproduce below:]
1. ... Having Project Viewer and Project Drop Down installed at the same time
2. ... Switching to a different project in Project Viewer, even when project drop-down is disabled, fires this error.

**Atom Version**: 1.5.3
**System**: Linux Mint
**Thrown From**: [project-dropdown](https://github.com/crot4lus/project-dropdown) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /home/jim/.atom/packages/project-dropdown/lib/project-dropdown.js:39

TypeError: Cannot read property 'split' of undefined
    at /home/jim/.atom/packages/project-dropdown/lib/project-dropdown.js:39:43
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.removePath (/usr/share/atom/resources/app.asar/src/project.js:281:22)
    at forEachOldPath (/home/jim/.atom/packages/project-viewer/lib/views/project-view.js:189:26)
    at Array.forEach (native)
    at project-view.bufferFiles (/home/jim/.atom/packages/project-viewer/lib/views/project-view.js:257:33)
    at project-view.clickProject (/home/jim/.atom/packages/project-viewer/lib/views/project-view.js:180:18)
```
### Commands

```
     -0:07.5.0 project-viewer:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter",
      "linter-jade",
      "linter-php",
      "punchclock"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.18.7
color-picker, v2.1.1
emmet, v2.4.1
file-icons, v1.6.15
git-diff-details, v0.23.0
git-go, v1.0.1
grunt-runner, v0.14.0
javascript-snippets, v1.2.1
less-than-slash, v0.12.3
node-debugger, v1.4.3
open_in_cmd, v0.6.0
package-sync, v1.0.0
pigments, v0.24.1
project-dropdown, v0.3.0
project-viewer, v0.2.30
release-notes, v0.53.0
simple-drag-drop-text, v0.3.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by GlennTaylorDigital** [comment]
This issue should be resolved in the latest release, please let me know if you have any further issues.

**Comment by drawcard** [comment]
Just encountered this error:

Uncaught TypeError: Cannot read property 'split' of undefined
/Users/drawcard/.atom/packages/project-dropdown/lib/project-dropdown.js:74
Hide Stack Trace
TypeError: Cannot read property 'split' of undefined
    at Object.setActiveProject (/Users/drawcard/.atom/packages/project-dropdown/lib/project-dropdown.js:74:46)
    at Object.createOptions (/Users/drawcard/.atom/packages/project-dropdown/lib/project-dropdown.js:135:29)
    at HTMLButtonElement.closeActiveProject (/Users/drawcard/.atom/packages/project-dropdown/lib/project-dropdown.js:90:25)
    at HTMLButtonElement.dispatch (/Users/drawcard/.atom/packages/project-dropdown/node_modules/jquery/dist/jquery.js:4737:27)
    at HTMLButtonElement.elemData.handle (/Users/drawcard/.atom/packages/project-dropdown/node_modules/jquery/dist/jquery.js:4549:28)
The error was thrown from the project-dropdown package. This issue has already been reported.
View Issue

**Comment by capsudo** [comment]
Same error on project-dropdown v0.13.0, atom 1.23.3, ubuntu 17.10.

```
TypeError: Cannot read property 'split' of undefined
    at Object.setActiveProject (/home/dri/.atom/packages/project-dropdown/lib/project-dropdown.js:74:46)
    at Object.createOptions (/home/dri/.atom/packages/project-dropdown/lib/project-dropdown.js:135:29)
    at Object.createDropdown (/home/dri/.atom/packages/project-dropdown/lib/project-dropdown.js:59:25)
    at HTMLDocument.<anonymous> (/home/dri/.atom/packages/project-dropdown/lib/project-dropdown.js:20:23)
    at fire (/home/dri/.atom/packages/project-dropdown/node_modules/jquery/dist/jquery.js:3187:31)
    at Object.fireWith [as resolveWith] (/home/dri/.atom/packages/project-dropdown/node_modules/jquery/dist/jquery.js:3317:7)
    at ready (/home/dri/.atom/packages/project-dropdown/node_modules/jquery/dist/jquery.js:3536:13)
```
